'use strict'

/*
|--------------------------------------------------------------------------
| CurrencySeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use('Factory')
const currency=use('App/Models/Currency')

class CurrencySeeder {
  async run () {
    try{
      let  currencies=[{iso:'KRW',name:'(South) Korean Won'},
        {iso:'AFA',name:'Afghanistan Afghani'},
      {iso:'ALL',name:'Albanian Lek'},
        {iso:'DZD',name:'Algerian Dinar'},
        {iso:'ADP',name:'Andorran Peseta'},
        {iso:'AOK',name:'Angolan Kwanza'},
        {iso:'ARS',name:'Argentine Peso'},
        {iso:'AMD',name:'Armenian Dram'},
        {iso:'AWG',name:'Aruban Florin'},
        {iso:'AUD',name:'Australian Dollar'},
        {iso:'BSD',name:'Bahamian Dollar'},
        {iso:'BHD',name:'Bahraini Dinar'},
        {iso:'BDT',name:'Bangladeshi Taka'},
        {iso:'BBD',name:'Barbados Dollar'},
        {iso:'BZD',name:'Belize Dollar'},
        {iso:'BMD',name:'Bermudian Dollar'},
        {iso:'BTN',name:'Bhutan Ngultrum'},
        {iso:'BOB',name:'Bolivian Boliviano'},
        {iso:'BWP',name:'Botswanian Pula'},
        {iso:'BRL',name:'Brazilian Real'},
        {iso:'GBP',name:'British Pound'},
        {iso:'BND',name:'Brunei Dollar'},
        {iso:'BGN',name:'Bulgarian Lev'},
        {iso:'BUK',name:'Burma Kyat'},
        {iso:'BIF',name:'Burundi Franc'},
        {iso:'CAD',name:'Canadian Dollar'},
        {iso:'CVE',name:'Cape Verde Escudo'},
        {iso:'KYD',name:'Cayman Islands Dollar'},
        {iso:'CLP',name:'Chilean Peso'},
        {iso:'CLF',name:'Chilean Unidades de Fomento'},
        {iso:'COP',name:'Colombian Peso'},
        {iso:'XOF',name:'Communauté Financière Africaine BCEAO - Francs'},
        {iso:'XAF',name:'Communauté Financière Africaine BEAC,name:Francs'},
        {iso:'KMF',name:'Comoros Franc'},
        {iso:'XPF',name:'Comptoirs Français du Pacifique Francs'},
        {iso:'CRC',name:'Costa Rican Colon'},
        {iso:'CUP',name:'Cuban Peso'},
        {iso:'CYP',name:'Cyprus Pound'},
        {iso:'CZK',name:'Czech Republic Koruna'},
        {iso:'DKK',name:'Danish Krone'},
        {iso:'YDD',name:'Democratic Yemeni Dinar'},
        {iso:'DOP',name:'Dominican Peso'},
        {iso:'XCD',name:'East Caribbean Dollar'},
        {iso:'TPE',name:'East Timor Escudo'},
        {iso:'ECS',name:'Ecuador Sucre'},
        {iso:'EGP',name:'Egyptian Pound'},
        {iso:'SVC',name:'El Salvador Colon'},
        {iso:'EEK',name:'Estonian Kroon {iso:EEK}'},
        {iso:'ETB',name:'Ethiopian Birr'},
        {iso:'EUR',name:'Euro'},
        {iso:'FKP',name:'Falkland Islands Pound'},
        {iso:'FJD',name:'Fiji Dollar'},
        {iso:'GMD',name:'Gambian Dalasi'},
        {iso:'GHC',name:'Ghanaian Cedi'},
        {iso:'GIP',name:'Gibraltar Pound'},
        {iso:'XAU',name:'Gold,name:Ounces'},
        {iso:'GTQ',name:'Guatemalan Quetzal'},
        {iso:'GNF',name:'Guinea Franc'},
        {iso:'GWP',name:'Guinea-Bissau Peso'},
        {iso:'GYD',name:'Guyanan Dollar'},
        {iso:'HTG',name:'Haitian Gourde'},
        {iso:'HNL',name:'Honduran Lempira'},
        {iso:'HKD',name:'Hong Kong Dollar'},
        {iso:'HUF',name:'Hungarian Forint'},
        {iso:'INR',name:'Indian Rupee'},
        {iso:'IDR',name:'Indonesian Rupiah'},
        {iso:'XDR',name:'International Monetary Fund {iso:IMF} Special Drawing Rights'},
        {iso:'IRR',name:'Iranian Rial'},
        {iso:'IQD',name:'Iraqi Dinar'},
        {iso:'IEP',name:'Irish Punt'},
        {iso:'ILS',name:'Israeli Shekel'},
        {iso:'JMD',name:'Jamaican Dollar'},
        {iso:'JPY',name:'Japanese Yen'},
        {iso:'JOD',name:'Jordanian Dinar'},
        {iso:'KHR',name:'Kampuchean {iso:Cambodian} Riel'},
        {iso:'KES',name:'Kenyan Schilling'},
        {iso:'KWD',name:'Kuwaiti Dinar'},
        {iso:'LAK',name:'Lao Kip'},
        {iso:'LBP',name:'Lebanese Pound'},
        {iso:'LSL',name:'Lesotho Loti'},
        {iso:'LRD',name:'Liberian Dollar'},
        {iso:'LYD',name:'Libyan Dinar'},
        {iso:'MOP',name:'Macau Pataca'},
        {iso:'MGF',name:'Malagasy Franc'},
        {iso:'MWK',name:'Malawi Kwacha'},
        {iso:'MYR',name:'Malaysian Ringgit'},
        {iso:'MVR',name:'Maldive Rufiyaa'},
        {iso:'MTL',name:'Maltese Lira'},
        {iso:'MRO',name:'Mauritanian Ouguiya'},
        {iso:'MUR',name:'Mauritius Rupee'},
        {iso:'MXP',name:'Mexican Peso'},
        {iso:'MNT',name:'Mongolian Tugrik'},
        {iso:'MAD',name:'Moroccan Dirham'},
        {iso:'MZM',name:'Mozambique Metical'},
        {iso:'NAD',name:'Namibian Dollar'},
        {iso:'NPR',name:'Nepalese Rupee'},
        {iso:'ANG',name:'Netherlands Antillian Guilder'},
        {iso:'YUD',name:'New Yugoslavia Dinar'},
        {iso:'NZD',name:'New Zealand Dollar'},
        {iso:'NIO',name:'Nicaraguan Cordoba'},
        {iso:'NGN',name:'Nigerian Naira'},
        {iso:'KPW',name:'North Korean Won'},
        {iso:'NOK',name:'Norwegian Kroner'},
      {iso:'OMR',name:'Omani Rial'},
      {iso:'PKR',name:'Pakistan Rupee'},
      {iso:'XPD',name:'Palladium Ounces'},
      {iso:'PAB',name:'Panamanian Balboa'},
      {iso:'PGK',name:'Papua New Guinea Kina'},
      {iso:'PYG',name:'Paraguay Guarani'},
      {iso:'PEN',name:'Peruvian Nuevo Sol'},
      {iso:'PHP',name:'Philippine Peso'},
      {iso:'XPT',name:'Platinum,name:Ounces'},
      {iso:'PLN',name:'Polish Zloty'},
      {iso:'QAR',name:'Qatari Rial'},
      {iso:'RON',name:'Romanian Leu'},
      {iso:'RUB',name:'Russian Ruble'},
      {iso:'RWF',name:'Rwanda Franc'},
      {iso:'WST',name:'Samoan Tala'},
      {iso:'STD',name:'Sao Tome and Principe Dobra'},
      {iso:'SAR',name:'Saudi Arabian Riyal'},
      {iso:'SCR',name:'Seychelles Rupee'},
      {iso:'SLL',name:'Sierra Leone Leone'},
      {iso:'XAG',name:'Silver,name:Ounces'},
      {iso:'SGD',name:'Singapore Dollar'},
      {iso:'SKK',name:'Slovak Koruna'},
      {iso:'SBD',name:'Solomon Islands Dollar'},
      {iso:'SOS',name:'Somali Schilling'},
      {iso:'ZAR',name:'South African Rand'},
      {iso:'LKR',name:'Sri Lanka Rupee'},
      {iso:'SHP',name:'St. Helena Pound'},
      {iso:'SDP',name:'Sudanese Pound'},
      {iso:'SRG',name:'Suriname Guilder'},
      {iso:'SZL',name:'Swaziland Lilangeni'},
      {iso:'SEK',name:'Swedish Krona'},
      {iso:'CHF',name:'Swiss Franc'},
      {iso:'SYP',name:'Syrian Potmd'},
      {iso:'TWD',name:'Taiwan Dollar'},
      {iso:'TZS',name:'Tanzanian Schilling'},
      {iso:'THB',name:'Thai Baht'},
      {iso:'TOP',name:'Tongan Paanga'},
      {iso:'TTD',name:'Trinidad and Tobago Dollar'},
      {iso:'TND',name:'Tunisian Dinar'},
      {iso:'TRY',name:'Turkish Lira'},
      {iso:'UGX',name:'Uganda Shilling'},
      {iso:'AED',name:'United Arab Emirates Dirham'},
      {iso:'UYU',name:'Uruguayan Peso'},
      {iso:'USD',name:'US Dollar'},
      {iso:'VUV',name:'Vanuatu Vatu'},
      {iso:'VEF',name:'Venezualan Bolivar'},
      {iso:'VND',name:'Vietnamese Dong'},
      {iso:'YER',name:'Yemeni Rial'},
      {iso:'CNY',name:'Yuan (Chinese) Renminbi'},
      {iso:'ZRZ',name:'Zaire Zaire'},
      {iso:'ZMK',name:'Zambian Kwacha'},
      {iso:'ZWD',name:'Zimbabwe Dollar'}];
      await currency.createMany(currencies)
    }catch (e) {
      console.log(e)
    }
  }
}

module.exports = CurrencySeeder
